/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Owner } from "./Owner";
export * as factories from "./factories";
export { Owner__factory } from "./factories/Owner__factory";
